{% set name = "python-build" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: b798f3f490c779fa88c99816ebee97ab636acd6630b1d91c8cf8eb8a4d922a19

build:
  number: 0
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.4
    - pip
  run:
    - python >3.4
    - importlib-metadata
    - packaging
    - pep517 >=0.9
    - toml

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  license: MIT
  license_file: LICENSE
  summary: A simple, correct PEP517 package builder

extra:
  recipe-maintainers:
    - ocefpaf
