{% set name = "python-build" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269

build:
  number: 0
  skip: True  # [py<36]
  noarch: python
  entry_points:
    - python-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
  run:
    - python >3.6
    - importlib-metadata >=0.22  # [py<38]
    - packaging >=19.0
    - pep517 >=0.9.1
    - toml

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help 
  requires:
    - pip
    - python <3.10

about:
  home: https://github.com/pypa/build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, correct PEP517 package builder
  dev_url: https://github.com/pypa/build
  doc_url: https://pypa-build.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
