{% set name = "python-build" %}
{% set version = "1.2.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: b36993e92ca9375a219c99e606a122ff365a760a2d4bba0caa09bd5278b608b7

build:
  number: 0
  skip: True  # [py<38]
  entry_points:
    - python-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - flit-core >=3.8
  run:
    - python
    - colorama  # [win]
    - packaging >=19.1
    - pyproject_hooks
    - importlib-metadata >=4.6  # [py<311]
    - tomli >=1.1.0  # [py<311]

test:
  imports:
    - build
  commands:
    - pip check
    - python-build --help 
  requires:
    - pip

about:
  home: https://github.com/pypa/build
  summary: A simple, correct PEP517 package builder
  description: |
    build manages pyproject.toml-based builds, invoking build-backend hooks 
    as appropriate to build a distribution package. It is a simple build tool 
    and does not perform any dependency management.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pypa/build
  doc_url: https://pypa-build.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
