{% set name = "python-build" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: 302c22c3ba2a0fd5f3911918651341ebb3896176cbdec15bd421f80b1afc7647

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - python-build = build.__main__:entrypoint
    - pyproject-build = build.__main__:entrypoint
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=3.11
  run:
    - python
    - colorama  # [win]
    - packaging >=24.0
    - pyproject_hooks
    - importlib-metadata >=4.6  # [py<311]
    - tomli >=1.1.0  # [py<311]

test:
  imports:
    - build
  source_files:
    - tests
    # Following files are required for some tests
    - pyproject.toml
    - src
    - README.md
    - LICENSE
  commands:
    - pip check
    - python-build --help
    - pyproject-build --help
    # 'test_output' is flaky
    # 'test_build_sdist' requires all files to be accessible from repo
    # 'test_uv_install_strips_pythonpath' requires the uv package, not available in -c main
    - pytest -vv tests -k "not test_output and not test_build_sdist and not test_uv_install_strips_pythonpath"
  requires:
    - pip
    - pytest >=6.2.4
    - pytest-mock >=2
    - pytest-rerunfailures >=9.1
    - filelock >=3
    - wheel >=0.36.0
    - virtualenv >=20.17  # [py<314]
    - virtualenv >=20.31  # [py>=314]
    - setuptools >= 42.0.0  # [py<310]
    - setuptools >= 56.0.0  # [py310]
    - setuptools >= 56.0.0  # [py311]
    - setuptools >= 67.8.0  # [py>=312]

about:
  home: https://build.pypa.io/
  summary: A simple, correct Python build frontend
  description: |
    build manages pyproject.toml-based builds, invoking build-backend hooks
    as appropriate to build a distribution package. It is a simple build tool
    and does not perform any dependency management.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pypa/build
  doc_url: https://pypa-build.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
